# Dependencies
markdown: redcarpet
highlighter: pygments
# Permalinks
permalink:        pretty

# Setup
title:            Jeno Karthic
tagline:          'Enthusiastic developer from Madurai,India'
description:      'Blog of jeno karthic'
url:              http://jenokarthic.github.io
baseurl:          http://jenokarthic.github.io/
disqus:              jenokarthicblog
author:
  name:           'Jeno Karthic'
  url:            https://twitter.com/jenokarthic

paginate:         5

# Custom vars
version:          1.0
exclude: [ 'Gemfile*', '_site/', '.code-highlighter-cache','.sass-cache' ]

