




# Dependencies






markdown: redcarpet
highlighter: pygments
# Permalinks
permalink:        /post/:title
relative_permalinks: true

exclude: [README.md, TODO.md,404.md]

# Setup
title:            Jeno Karthic
tagline:          'Enthusiastic developer from Madurai,India'
description:      'Blog of jeno karthic'
url:              http://jenokarthic.github.io
baseurl:          /

author:
  name:           'Jeno Karthic'
  url:            https://twitter.com/jenokarthic

paginate:3
paginate_path: '/blog/:num'

# Custom vars
version:          1.0

